### ISSUE TITLE
Add bytes_per_line to the constructor of QImage()

### ISSUE THREAD

**Issue by b-z** [NathanZabriskie/GraphCut#1]
```
    @staticmethod
    def get_qimage(cvimage):
        print(cvimage.shape)
        height, width, bytes_per_pix = cvimage.shape
        bytes_per_line = width * bytes_per_pix;
        cv2.cvtColor(cvimage, cv2.COLOR_BGR2RGB, cvimage)
        return QImage(cvimage.data, width, height, bytes_per_line, QImage.Format_RGB888)
```

Otherwise the image will display abnormally.

**Comment by zhaoxiaoqian666** [comment]
Traceback (most recent call last):
  File "F:/GraphCut-master1/GraphCut-master/NewCutUI.py", line 161, in <module>
    newUI = NewCutUI()
  File "F:/GraphCut-master1/GraphCut-master/NewCutUI.py", line 12, in __init__
    self.graph_maker = GraphMaker.GraphMaker()
TypeError: __init__() missing 2 required positional arguments: 'filename' and 'outfilename'

Process finished with exit code 1

**Comment by zhaoxiaoqian666** [comment]
上面的问题应该怎么改啊？求教。
